In [20]:
import numpy as np


In [27]:
import ga

In [21]:
# The equation I want to implement using genetic algorithm
# Y = w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + w6x6

# from the equation, 6 inputs (x1 to x6), 6 weights (w1 to w6)

equation_inputs = [8,-1,6.7,10,-6,-2.1]

In [22]:
# Number of weights to optimize is 6
num_weights = 6

In [23]:
# To determine the population size, we find the number of chromozones (individuals or solution) first
sol_per_pop = 8


In [24]:
# Each population will have sol_per_pop chromosomes and num_weights number of weights per chromosome
pop_size = (sol_per_pop, num_weights)

In [25]:
# Defining the initial population
new_pop = np.random.uniform(low=-4.0, high=4.0, size=pop_size)

In [26]:
new_pop

array([[-2.45652603,  3.29604857,  0.73132508, -1.57562012, -1.39032804,
        -1.82072797],
       [ 1.79399097, -0.95077563,  2.45181927,  0.3079981 , -3.3269522 ,
         0.73557844],
       [-2.98523921,  2.65607052, -2.11009289, -2.6194843 ,  0.07064079,
        -0.49222351],
       [ 3.2388145 ,  0.28018512, -1.08219749, -3.95694213,  2.70987788,
        -1.25407519],
       [ 0.0211209 , -0.98375243, -0.6650934 , -0.13712156,  0.27269635,
        -2.8060222 ],
       [-3.28376405, -1.8829552 ,  1.38700343,  3.45699163, -0.34393904,
        -2.8666912 ],
       [-3.26650126, -3.25095824, -2.09252583,  2.85496694,  3.84440908,
         1.51105659],
       [-3.93561103,  1.70092026,  0.5004965 , -2.26918458, -1.90984105,
         3.87657502]])

In [28]:
# Now, let's select the mating parent from the current pop based on fitness value.

num_generations = 5

num_parents_mating = 4
for generation in range(num_generations):
     # Measuring the fitness of each chromosome in the population.
     fitness = ga.cal_pop_fitness(equation_inputs, new_pop)
    # Selecting the best parents in the population for mating.
     parents = ga.select_mating_pool(new_pop, fitness, 
                                       num_parents_mating)
 
     # Generating next generation using crossover.
     offspring_crossover = ga.crossover(parents,
                                        offspring_size=(pop_size[0]-parents.shape[0], num_weights))
 
     # Adding some variations to the offsrping using mutation.
     offspring_mutation = ga.mutation(offspring_crossover)
# Creating the new population based on the parents and offspring.
     new_pop[0:parents.shape[0], :] = parents
     new_pop[parents.shape[0]:, :] = offspring_mutation

In [29]:
new_pop

array([[ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.94960347],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.70557161],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.69518609],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.3462774 ],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.02609207],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -3.45458621],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -2.43779127],
       [ 1.79399097, -0.95077563,  2.45181927,  3.45699163, -0.34393904,
        -4.30273543]])

In [31]:

import numpy
import ga

"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""

# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""
sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
new_pop = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_pop)

num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    # Measing the fitness of each chromosome in the population.
    fitness = ga.cal_pop_fitness(equation_inputs, new_pop)

    # Selecting the best parents in the population for mating.
    parents = ga.select_mating_pool(new_pop, fitness, 
                                      num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = ga.crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = ga.mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
    new_pop[0:parents.shape[0], :] = parents
    new_pop[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
    print("Best result : ", numpy.max(numpy.sum(new_pop*equation_inputs, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
fitness = ga.cal_pop_fitness(equation_inputs, new_pop)
# Then return the index of that solution corresponding to the best fitness.
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_pop[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])


[[-3.66982509 -0.41879217 -2.97454137  2.10686756  3.8637201  -3.42849107]
 [-1.90079855 -2.33472622  2.55590421  3.33466641  0.31285582 -0.96473913]
 [ 0.83297622  3.26311759 -2.47661712  1.95286466  3.22676169 -3.98868032]
 [-1.76970463 -0.15561997  3.59331716  3.16167198  3.08399544 -3.98993815]
 [-2.32012423 -3.40543998 -1.86103792  3.41694362 -1.29752512  1.74120144]
 [ 0.68524186 -3.4790665  -0.78315379 -2.6455239  -0.14174482  1.82586863]
 [ 0.1432976   3.96937835  0.09088083 -1.28174592  2.15271483 -3.34852179]
 [-3.44802014 -2.40420648  3.4926301   0.44830169  1.23148044  3.20927986]]
Generation :  0
Best result :  27.19289272858535
Generation :  1
Best result :  32.4478981475944
Generation :  2
Best result :  34.311498328151764
Generation :  3
Best result :  37.1935724135806
Generation :  4
Best result :  38.33521943400681
Best solution :  [[[ 0.68524186 -3.4790665  -0.78315379  3.41694362 -1.29752512
   -0.00418358]]]
Best solution fitness :  [38.33521943]
